language: python
cache: pip

sudo: false

python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "9.5"

env:
  global:
    - PGUSER=postgres
  matrix:
    - DJANGO=2.0

matrix:
  fast_finish: true
  include:
    - { python: "3.6", env: DJANGO=2.0 }
    - { python: "3.6", env: TOXENV=isort }

install:
  - pip install tox tox-travis

before_script:
  - psql -c 'create database ctrlz;' -U postgres
  - psql -c 'create database ctrlz2;' -U postgres

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO

notifications:
  email: false
