dist: xenial
language: python
cache: pip

sudo: false

python:
  - "3.5"
  - "3.6"
  - "3.7"

services:
  - postgresql

addons:
  postgresql: "10"

env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=
  matrix:
    - DJANGO=1.11
    - DJANGO=2.0
    - DJANGO=2.1
    - DJANGO=2.2

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=isort

    - python: "3.6"
      env: TOXENV=docs

install:
  - pip install tox-travis

before_script:
  - psql -c 'create database ctrlz;' -U postgres
  - psql -c 'create database ctrlz2;' -U postgres

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO

notifications:
  email: false
